import { getDocsClient, getDriveClient } from "./googleAuth.js";

/**
 * Reads the plain-text content of any Google Doc (or Doc-convertible file)
 * via Drive export. Used for the template/rules doc, brief docs, and
 * reference script docs - all read-only.
 */
export async function fetchDocPlainText(docId) {
  const drive = getDriveClient();
  const response = await drive.files.export(
    { fileId: docId, mimeType: "text/plain" },
    { responseType: "text" }
  );
  return typeof response.data === "string" ? response.data : String(response.data);
}

/**
 * Small text builder that tracks character ranges tagged with a style, so we
 * can turn a plain script into a formatted Google Doc in one batchUpdate.
 */
class ScriptDocBuilder {
  constructor() {
    this.text = "";
    this.spans = []; // { start, end, style: "HEADING_1" | "HEADING_2" | "BOLD" }
  }

  raw(str) {
    this.text += str;
    return this;
  }

  line(str = "") {
    this.text += str + "\n";
    return this;
  }

  styledLine(str, style) {
    const start = this.text.length;
    this.text += str;
    this.spans.push({ start, end: this.text.length, style });
    this.text += "\n";
    return this;
  }

  blank() {
    this.text += "\n";
    return this;
  }
}

function appendVariant(b, variant, showVariantHeading) {
  if (showVariantHeading) {
    b.styledLine(`Wariant: ${variant.variantLabel}`, "HEADING_1");
    b.blank();
  }

  b.styledLine("Rolka - skrypt:", "HEADING_2");
  b.blank();
  b.styledLine("Hook:", "BOLD");
  b.line(variant.rolka.hook);
  b.blank();

  if (variant.rolka.hookVariantB) {
    b.styledLine("Hook B (wariant testowy):", "BOLD");
    b.line(variant.rolka.hookVariantB);
    b.blank();
  }

  variant.rolka.body.forEach((kwestia, i) => {
    b.styledLine(`Kwestia ${i + 1}:`, "BOLD");
    b.line(kwestia);
    b.blank();
  });

  b.styledLine("Promocja:", "BOLD");
  b.line(variant.rolka.promocja);
  b.blank();

  b.styledLine("CTA:", "BOLD");
  b.line(variant.rolka.cta);
  b.blank();
  b.line("________________________________");
  b.blank();

  b.styledLine("Krotsza rolka - skrypt:", "HEADING_2");
  b.blank();
  b.line(variant.krotszaRolka.tekst);
  b.blank();
  b.blank();
}

/**
 * Builds the full plain-text content + formatting spans for ALL script
 * variants from one !skrypt request in a single document (one link per
 * request, not one link per variant), each following the ITM template
 * (Hook -> Kwestia 1..N -> Promocja -> CTA, then a condensed "Krotsza rolka"
 * version), and appends the recording-instructions placeholder heading once
 * at the very end (never generated by the AI).
 */
export function buildScriptDocContent(docTitle, variants, recordingInstructionsText) {
  const b = new ScriptDocBuilder();

  b.styledLine(docTitle, "HEADING_1");
  b.blank();

  variants.forEach((variant) => appendVariant(b, variant, variants.length > 1));

  b.styledLine(recordingInstructionsText, "HEADING_2");

  return { text: b.text, spans: b.spans };
}

function spansToRequests(spans) {
  const requests = [];
  for (const span of spans) {
    // Google Docs body content starts at index 1.
    const range = { startIndex: span.start + 1, endIndex: span.end + 1 };
    if (span.style === "BOLD") {
      requests.push({
        updateTextStyle: {
          range,
          textStyle: { bold: true },
          fields: "bold",
        },
      });
    } else {
      requests.push({
        updateParagraphStyle: {
          range,
          paragraphStyle: { namedStyleType: span.style },
          fields: "namedStyleType",
        },
      });
    }
  }
  return requests;
}

/**
 * Creates a new Google Doc with the given title and formatted content.
 * Returns the new doc's id.
 */
export async function createFormattedScriptDoc(title, text, spans) {
  const docs = getDocsClient();

  const created = await docs.documents.create({ requestBody: { title } });
  const documentId = created.data.documentId;

  const requests = [{ insertText: { location: { index: 1 }, text } }, ...spansToRequests(spans)];

  await docs.documents.batchUpdate({ documentId, requestBody: { requests } });

  return documentId;
}

/**
 * Moves a Drive file into the given target folder (removing any prior
 * parents), e.g. to file a newly-created script doc into the shared scripts
 * folder.
 */
export async function moveDocToFolder(fileId, targetFolderId) {
  const drive = getDriveClient();
  // supportsAllDrives is required whenever a Shared Drive is involved (either
  // the file or, as here, the target parent folder) - without it the Drive
  // API v3 silently reports "File not found" even with full Manager access.
  const file = await drive.files.get({ fileId, fields: "parents", supportsAllDrives: true });
  const previousParents = (file.data.parents || []).join(",");

  await drive.files.update({
    fileId,
    addParents: targetFolderId,
    removeParents: previousParents,
    fields: "id, parents",
    supportsAllDrives: true,
  });
}
