import { GOOGLE_SCRIPT_TEMPLATE_DOC_ID } from "../config.js";
import { fetchDocPlainText } from "./googleDocs.js";

const INSTRUCTIONS_MARKER = "Zalacznik: wskazowki nagraniowe dla klienta";

function stripPolishDiacritics(str) {
  return str
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/ł/g, "l")
    .replace(/Ł/g, "L");
}

let cachedTemplate = null;

/**
 * Fetches and caches the ITM script style-guide doc once per process
 * lifetime (network + generation-prompt tokens are only spent once, not on
 * every !skrypt invocation). The doc is split into:
 *  - rulesText: structure/style rules fed to Claude as the (cached) system prompt
 *  - recordingInstructionsText: the client-facing recording instructions,
 *    appended verbatim to every generated doc, never regenerated by the AI.
 * Pass forceRefresh: true (via an admin subcommand) if the template doc changes.
 */
export async function getScriptTemplate({ forceRefresh = false } = {}) {
  if (cachedTemplate && !forceRefresh) return cachedTemplate;

  const fullText = await fetchDocPlainText(GOOGLE_SCRIPT_TEMPLATE_DOC_ID);
  const normalizedFull = stripPolishDiacritics(fullText);
  const markerIndex = normalizedFull
    .toLowerCase()
    .indexOf(INSTRUCTIONS_MARKER.toLowerCase());

  if (markerIndex === -1) {
    throw new Error(
      `Nie znaleziono sekcji "${INSTRUCTIONS_MARKER}" w dokumencie szablonu skryptow.`
    );
  }

  cachedTemplate = {
    rulesText: fullText.slice(0, markerIndex).trim(),
    recordingInstructionsText: fullText.slice(markerIndex).trim(),
    fetchedAt: new Date(),
  };

  return cachedTemplate;
}
